name: greet
on: 
  workflow_dispatch:
    inputs:
      name:
        description: "The name of the person to greet"
        required: true
        type: string
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "hello, ${{ github.event.inputs.name }}!, or github actor: ${{ github.actor }} or env var: $GITHUB_ACTOR"